### ISSUE TITLE
Parcel crashing on onRestoreInstanceState

### ISSUE THREAD

**Issue by bernaferrari** [Ramotion/fluid-slider-android#19] opened 2018-07-24 05:30 UTC
Steps to reproduce:
- Download project
- Run app
- Close it
- Tap on the red square button on Logcat's left size (this will terminate the app and force onSaveInstanceState)
- Open it again
- Crash!

Log:
   ```
2018-07-24 02:27:13.288 30935-30935/com.ramotion.fluidslider.example.simple E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ramotion.fluidslider.example.simple, PID: 30935
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ramotion.fluidslider.example.simple/com.ramotion.fluidslider.example.simple.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@cdc64f7: Unmarshalling unknown type code 7209057 at offset 440
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@cdc64f7: Unmarshalling unknown type code 7209057 at offset 440
        at android.os.Parcel.readValue(Parcel.java:2771)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3140)
        at android.os.Parcel.readSparseArray(Parcel.java:2354)
        at android.os.Parcel.readValue(Parcel.java:2749)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3059)
        at android.os.BaseBundle.unparcel(BaseBundle.java:257)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:958)
        at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2246)
        at android.app.Activity.onRestoreInstanceState(Activity.java:1153)
        at android.app.Activity.performRestoreInstanceState(Activity.java:1108)
        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1266)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Comment by rayliverified** [comment] 2018-08-28 21:16
I have this problem as well. 
```
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity 
android.view.InflateException: Binary XML file line #39: Binary XML file line #39: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: android.view.InflateException: Binary XML file line #39: Binary XML file line #39: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #39: Error inflating class fragment
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@2260875: Unmarshalling unknown type code 4259886 at offset 700
        at android.os.Parcel.readValue(Parcel.java:2771)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3140)
        at android.os.Parcel.readSparseArray(Parcel.java:2354)
        at android.os.Parcel.readValue(Parcel.java:2749)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3059)
        at android.os.BaseBundle.unparcel(BaseBundle.java:257)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:958)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1361)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3223)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1523)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1494)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:197)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2417)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1684)
        at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3774)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:120)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:405)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:387)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.treatmyocd.nocd.MainActivity.onCreate(MainActivity.kt:52)
        at android.app.Activity.performCreate(Activity.java:7174)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
2018-08-28 16:15:56.611 21624-21624/com.treatmyocd.nocd.dev E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by rayliverified** [comment] 2018-08-28 21:17
Anytime a screen with Fluid Layout is saved in the background, it crashes when the app tries to restore itself.

**Comment by rayliverified** [comment] 2018-09-06 18:58
Any updates on whether this will be fixed? This is a very serious bug that makes it difficult to use this library in production.

**Comment by dvg4000** [comment] 2018-09-06 19:31
I can't reproduce this error in example project. Can you give me link to github (or whatever) project where this error can be reproduced?

**Comment by bernaferrari** [comment] 2018-09-06 20:00
Are you testing it with onRestart and onSaveInstanceState? It is fully reproducible here.

**Comment by rayliverified** [comment] 2018-09-10 20:30
Try putting this in a fragment instead of an activity. That's how you get the crash.

**Comment by golovin47** [comment] 2019-02-05 04:54
This issue was resolved by payasgupta's commit.

**Closed as completed by golovin47** 2019-02-05 04:54 UTC
